name: Test with uv and pytest

on:
  push:
    branches: 
      - main
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies with uv
        run: uv sync --dev
      - name: Run tests with uv and pytest
        run: uv run pytest
